### ISSUE TITLE
Unable to use snippets

### ISSUE THREAD

**Issue by stephangrobler** [jmiazga/angularjs-styleguide-snippets#12]
It seems as though the snippets are not accessible an Atom 1.13.1, I am able to use them if I copy and paste into my own snippets.cson file.

**Comment by jmiazga** [comment]
Hmm, I don't seem to have an issue with 1.14.0.  What os are you on?

**Comment by stephangrobler** [comment]
I am on windows 10, I also just installed the package on my atom at home with 1.14.0 and windows 10

**Comment by stephangrobler** [comment]
I am able to use it now, just restarted 👍 thanks for responding and sorry for making you look at a non-issue, know how it feels 🥇
