### ISSUE TITLE
Consider adding ng Ingect comments

### ISSUE THREAD

**Issue by danielo515** [jmiazga/angularjs-styleguide-snippets#3]
Hello,

 `/** @ngInject */` comments are part of John Papa's style guide recommendations. Would you coonsier adding them to the snippets?

Regards

**Comment by jmiazga** [comment]
I originally included ngInject in my snippets, but John Papa had me remove them before he accepted my pull request. They do not apply to everyone, only those who use task runners like gulp or grunt.

**Comment by danielo515** [comment]
Ok, thank you for the explanation.
I thought that as long as they are just comments, they will not hurt anyone.

Regards

**Comment by jmiazga** [comment]
It looks like the other snippets do include ngInject now. If you want to create a pull request Ill merge in the changes, and update the package.

**Comment by jmiazga** [comment]
Added ngInclude in v0.7.3
