### ISSUE TITLE
Angularjs 1.5 Component

### ISSUE THREAD

**Issue by mort3za** [jmiazga/angularjs-styleguide-snippets#5]
Please add angular 1.5 component to the list.
Thanks for these awesome snippets.

**Comment by jmiazga** [comment]
Until John Papa releases his recommendation, I am going to hold off adding this. You can always create your own snippet in the mean time: https://atom.io/docs/latest/using-atom-snippets#creating-your-own-snippets

**Comment by mackelito** [comment]
Any updates on this?

**Comment by mort3za** [comment]
@mackelito I just created my snippets (a frok of this repo with some modifications) here: https://atom.io/packages/angularjs1x-styleguide-snippets
Use it if you like.

**Comment by mackelito** [comment]
@mort3za I actually create a PR to this repo and it has been merged 👍
