### ISSUE TITLE
Add support for component

### ISSUE THREAD

**Issue by mackelito** [jmiazga/angularjs-styleguide-snippets#6]
Now I know that the johnpapa style guide is not updated with this yet but it should be added soon ;)
In angular 1.5 there is support for .component and should be used instead on .directive (in most cases)

**Comment by jmiazga** [comment]
Until John Papa releases his recommendation, I am going to hold off adding this. You can always create your own snippet in the mean time: https://atom.io/docs/latest/using-atom-snippets#creating-your-own-snippets

**Comment by jmiazga** [comment]
Thanks for the pr!
