### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by dirkpostma** [jmiazga/angularjs-styleguide-snippets#7]
I just spent about an hour to get these snippets working. The problem was that I didn't install language-ts package. If I'm right, the scope wasn't recognized and therefore the snippets were not working.

Am I correct..? If so, I'd like to suggest that you add a note in documentation that package language-ts is required.

**Comment by jmiazga** [comment]
I am not sure why this would require language-ts. These snippets are for angular 1 written in javascript.
